# Generated by Django 5.2.2 on 2025-06-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('admin', 'administrador'), ('profissional', 'Profissional de Saúde'), ('paciente', 'Paciente')], max_length=20),
        ),
    ]
